### ISSUE TITLE
NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by mehmetaliuluc** [nickpagz/3commas-ftx-triggers#11]
Dear 

when i run the   "Py3c_create.py"  i got some error would you please help me for solution

**Config File**
TC_ACCOUNT_ID = '31369776'
TC_API_KEY = 'xxxxx'
TC_API_SECRET = 'xxxxxx'
BASE_URL = 'https://api.3commas.io'

API_KEY = 'xxxxx'
SECRET_KEY = 'xxxxx'
SUB_ACCOUNT = ''
PAIRS_BLACKLIST = ['DMG-PERP', 'BRZ-PERP', 'PERP/USD', 'SRN-PERP', 'PRIV-PERP']
LTF_DELAY = 60 #seconds between getting latest market data, processing orders.
LTF_INTERVALS = 5 # Delay * Intervals gives us the total time before the first order
LTF_BULL_CHANGE = 2.0
LTF_BEAR_CHANGE = -2.0
MAX_OPEN_POSITIONS = 20
ORDER_VALUE = 10
TAKE_PROFIT = '0.06'
STOP_LOSS = '0.03'
FUNDS_USAGE = 0.9
SWITCH_PERCENT = -7.0
TREND_STRENGTH = 65  #  Percentage of longs vs shorts to consider not trading against a trend.
OPEN_POSITION_PRIORITY = True # True for max open positions, False for order size #not used in 3Commas, atm

**ERROR**
runfile('E:/malibot/Py3c_create.py', wdir='E:/malibot')
Reloaded modules: config
no existing bot ID files found, proceeding....
Error: {'error': True, 'msg': 'Other error occurred: not_found Not Found None.'}
Traceback (most recent call last):

  File "E:\malibot\Py3c_create.py", line 175, in <module>
    build_bots()

  File "E:\malibot\Py3c_create.py", line 150, in build_bots
    longbot_list, no_long_bots = generate_long_bots(pairs_list, min_price)

  File "E:\malibot\Py3c_create.py", line 81, in generate_long_bots
    bot_list[key] = data["id"]

TypeError: 'NoneType' object is not subscriptable

**Comment by nickpagz** [comment]
@mehmetaliuluc If no bots are getting created at all, then make sure you're using the correct account for 3Commas. Quite a few people have had difficulties with this since 3Commas doesn't make it obvious. Have a look at this comment:

https://onepercent.blog/2021/08/09/make-three-thousand-percent-returns-trading-bots-3commas/comment-page-1/#comment-69

...to check your account id.
